version: "3.8"
services:
    server:
        build:
            context: . # specify the build context directory
        ports:
            - 9090:9090
        depends_on:
            - mysqldb
    mysqldb:
        image: "mysql:8.0.36"
        # restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: Ticket_Reservation_System
            # MYSQL_USER: root
            MYSQL_PASSWORD: Admin@Hazem213
            MYSQL_ROOT_PASSWORD: Admin@Hazem213
